version: '3.9'

networks:
  chroma-net:
    driver: bridge

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb-server
    restart: unless-stopped
    volumes:
      - ./data/chroma-data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=TRUE
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    ports:
      - "18000:8000"  # Host port 18000 -> Container port 8000
    networks:
      - chroma-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s