version: '3.9'

networks:
  chroma-net:
    driver: bridge

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: musequill-chromadb-server
    restart: unless-stopped
    volumes:
      - ./data/chroma-data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=TRUE
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    ports:
      - "18000:8000"  # Host port 18000 -> Container port 8000
    networks:
      - chroma-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: musequill-redis-server
    restart: unless-stopped
    volumes:
      - ./data/redis-data:/data
    environment:
      # Redis configuration
      - REDIS_SAVE=900 1 300 10 60 10000  # Persistence settings
      - REDIS_MAXMEMORY=256mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    ports:
      - "16379:6379"  # Host port 16379 -> Container port 6379
    networks:
      - chroma-net
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Redis Commander for GUI management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin123  # Change this in production
    ports:
      - "18081:8081"
    networks:
      - chroma-net
    depends_on:
      redis:
        condition: service_healthy
    profiles:
      - tools  # Only start with: docker-compose --profile tools up